// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webpush/protobuf/push_subscription.proto

package webpush_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// https://www.w3.org/TR/2017/WD-push-api-20171215/
// `PushSubscription` represents a push subscription described in 4.3.
type PushSubscription struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh               []byte   `protobuf:"bytes,2,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth                 []byte   `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushSubscription) Reset()         { *m = PushSubscription{} }
func (m *PushSubscription) String() string { return proto.CompactTextString(m) }
func (*PushSubscription) ProtoMessage()    {}
func (*PushSubscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_push_subscription_04fc4b0fbbc25837, []int{0}
}
func (m *PushSubscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushSubscription.Unmarshal(m, b)
}
func (m *PushSubscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushSubscription.Marshal(b, m, deterministic)
}
func (dst *PushSubscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSubscription.Merge(dst, src)
}
func (m *PushSubscription) XXX_Size() int {
	return xxx_messageInfo_PushSubscription.Size(m)
}
func (m *PushSubscription) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSubscription.DiscardUnknown(m)
}

var xxx_messageInfo_PushSubscription proto.InternalMessageInfo

func (m *PushSubscription) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *PushSubscription) GetP256Dh() []byte {
	if m != nil {
		return m.P256Dh
	}
	return nil
}

func (m *PushSubscription) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

func init() {
	proto.RegisterType((*PushSubscription)(nil), "webpush.protobuf.PushSubscription")
}

func init() {
	proto.RegisterFile("webpush/protobuf/push_subscription.proto", fileDescriptor_push_subscription_04fc4b0fbbc25837)
}

var fileDescriptor_push_subscription_04fc4b0fbbc25837 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x4f, 0x4d, 0x2a,
	0x28, 0x2d, 0xce, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x07, 0xf1, 0xe2,
	0x8b, 0x4b, 0x93, 0x8a, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0x32, 0xf3, 0xf3, 0xf4, 0xc0, 0x52, 0x42,
	0x02, 0x50, 0x95, 0x7a, 0x30, 0x95, 0x4a, 0x51, 0x5c, 0x02, 0x01, 0xa5, 0xc5, 0x19, 0xc1, 0x48,
	0x6a, 0x85, 0xa4, 0xb8, 0x38, 0x52, 0xf3, 0x52, 0x0a, 0xf2, 0x33, 0xf3, 0x4a, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x31, 0x2e, 0xb6, 0x02, 0x23, 0x53, 0xb3, 0x94, 0x0c,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x28, 0x4f, 0x48, 0x88, 0x8b, 0x25, 0xb1, 0xb4, 0x24,
	0x43, 0x82, 0x19, 0x2c, 0x0a, 0x66, 0x3b, 0xa9, 0x71, 0xa9, 0x24, 0xe7, 0xe7, 0xea, 0xa5, 0x67,
	0x96, 0x64, 0x94, 0x26, 0xe9, 0xe5, 0xe5, 0x67, 0x27, 0xe6, 0xe6, 0x97, 0xe4, 0xeb, 0xa1, 0xbb,
	0x21, 0x89, 0x0d, 0xcc, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x9b, 0xed, 0xae, 0xc8,
	0x00, 0x00, 0x00,
}
