version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nokamoto/webpush-service-go
    steps:
      - checkout
      - run:
          name: gofmt
          command: |
            test -z "$(gofmt -l ./*.go)"
      - run:
          name: lint
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./*.go
      - run:
          name: test
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure -vendor-only=true
            go test .
  dist:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build & push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./build.sh --push
workflows:
  version: 2
  ci:
    jobs:
      - build
      - dist:
          requires:
            - build
